defaults:
  -
    scope:
      path: ""
    values:
      layout: index
      description: Programmer with experience in fullstack and game development, using a variety of languages.
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: :title
