defaults:
  -
    scope:
      path: ""
    values:
      layout: index
      description: Programming portfolio
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: :title
